name: Build and Deploy ACE-CRM(Higher)

on:
  workflow_dispatch:
    inputs:
      ace_version:
        description: 'ACE version to be used for build and deployment'
        required: true
        default: '12.0.12.7'
  push:
    branches:
      - release/*

env:
  ARTIFACTORY_REPOSITORY: ax-crm
  ARTIFACTORY_PATH: developerfiles
  MQSI_PATH: '/runner/_work/ACE-CRM/ACE-CRM/ace-12.0.12.7'
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  ArtifactsFrom: ../BuildAndDeploy/Build_Release

jobs:
  setup:
    runs-on: ecp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set ACE Version variable
        id: set_ace_version
        run: |
          ACE_VERSION=${{ github.event.inputs.ace_version || '12.0.12.7' }}
          echo "version=${ACE_VERSION}" >> $GITHUB_OUTPUT

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.ARTIFACTORY_HOST }}
          JF_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Download and Unpack ACE Developer Tools
        run: |
          jf rt dl "ax-crm/developerfiles/${{ steps.set_ace_version.outputs.version }}-ACE-LINUX64-DEVELOPER.tar.gz" --flat=true
          tar -xvf "${{ steps.set_ace_version.outputs.version }}-ACE-LINUX64-DEVELOPER.tar.gz"

      - name: Set up ACE Path
        shell: bash
        run: |
          set -e
          echo "ACE Path: $MQSI_PATH"

      - name: Install dependencies
        run: |
          sudo apt-get install --reinstall -y ca-certificates
          sudo apt-get install -y xvfb
          sudo apt-get install -y openjdk-11-jdk
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          source ~/.bashrc
          echo $JAVA_HOME
          java -version
          Xvfb :99 -ac &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Build BAR files
        run: |
          apps=(
            CIFPolicySetsBindings
            CCPolicySetsBindings
            PhoenixPolicySetBindings
            Common_Library
            Common_Library_Java
            ClaimsAPI_Library
            PhoenixAPILibrary
            SOAPCIFMDMv11Library
            REST_SF_TO_CIF_HUB
            ACE_AUDIT_ERROR_LOGGING_MFP
            CIF_TO_SF_ASYNC_PARTY_MFP
            CIF_TO_SF_ASYNC_POLICY_MFP
            PC_TO_SF_ASYNC_MFP
            SF_TO_CIF_ASYNC_MFP
            CIF_TO_ACE_NOTIFICATION_MFP
            CIF_TO_SF_RETRY_ERROR_MFP
            DS_TO_SF_ASYNC_MFP
            REST_TO_CC_HUB
            CC_TO_SF_ASYNC_MFP
            REST_TO_CIF_HUB
            REST_SF_TO_LIFE_HUB
            ACE_TO_SF_PLATFORM_EVENT_MFP
            SF_TO_ACE_GROUP_EVENT_MFP
            SF_TO_ACE_PARTY_EVENT_MFP
            SFPolicySetsBindings
          )
          for app in "${apps[@]}"; do
            echo "Building BAR file for $app"
            "${MQSI_PATH}/tools/mqsicreatebar" -data workspace -b "${app}.bar" -a "${app}" -cleanBuild -deployAsSource
            mkdir -p bars
            mv "${app}.bar" "bars/${app}.bar"
          done

      - name: Upload BARs
        uses: actions/upload-artifact@v4
        with:
          name: bar-artifacts
          path: bars/*.bar

  deploy_situat:
    needs: setup
    uses: ./.github/workflows/deploy-ace-crm.yaml
    with:
      environment: situat

  deploy_sit2:
    needs: setup
    uses: ./.github/workflows/deploy-ace-crm.yaml
    with:
      environment: sit2

  deploy_training:
    needs: setup
    uses: ./.github/workflows/deploy-ace-crm.yaml
    with:
      environment: training

  deploy_partner:
    needs: setup
    uses: ./.github/workflows/deploy-ace-crm.yaml
    with:
      environment: partner

  deploy_preprod:
    needs: [deploy_situat]
    uses: ./.github/workflows/deploy-ace-crm.yaml
    with:
      environment: preprod

  deploy_prod:
    needs: deploy_preprod
    uses: ./.github/workflows/deploy-ace-crm.yaml
    with:
      environment: prod
