name: Merge dev into main

on:
  workflow_dispatch:  # Manual trigger

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history needed for merges

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest main
        run: git pull origin main

      - name: Merge dev into main
        run: |
          git merge origin/dev --no-ff -m "Merge branch 'dev' into main"

      - name: Configure Git for PAT push
        run: |
          git config --global user.email "csenapati12@gmail.com"
          git config --global user.name "csenapati12"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Push changes
        run: git push origin main
