name: List Read-Only (Protected) Branches

on:
  workflow_dispatch:

jobs:
  list-readonly-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: List protected (read-only) branches
        run: |
          echo "Read-only (protected) branches in the repository:"
          gh api repos/${{ github.repository }}/branches --paginate \
            | jq -r '.[] | select(.protected) | .name'
