name: Restore Deleted Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of the branch to restore"
        required: true
      commit_sha:
        description: "Commit SHA to restore the branch from"
        required: true

jobs:
  restore-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Default Branch
        uses: actions/checkout@v4

      - name: Recreate Deleted Branch
        run: |
          git config --global user.email "csenapati12@gmail.com"
          git config --global user.name "csenapati12"
          git fetch origin ${{ github.event.inputs.commit_sha }}
          git branch ${{ github.event.inputs.branch_name }} ${{ github.event.inputs.commit_sha }}
          git push origin ${{ github.event.inputs.branch_name }}
